[package]
name = "unbin"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
thiserror = "2.0"

[dev-dependencies]
once_cell = "1.20"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.13"
