[package]
name = "unbin"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.13"
